spring.application.name=PROYECTO-TALLER


spring.datasource.url=jdbc:postgresql://localhost:5432/taller_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true